# Generated by Django 3.1 on 2020-09-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0007_auto_20200905_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
