# Generated by Django 3.1 on 2020-09-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0008_auto_20200909_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='name',
            new_name='user_id',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
